"""generate table migration

Revision ID: 8fd97315e8b0
Revises: 
Create Date: 2021-10-30 12:01:42.038627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd97315e8b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stra_number', sa.String(length=50), nullable=True),
    sa.Column('sipa_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('pharmacy_name', sa.String(length=50), nullable=True),
    sa.Column('pharmacy_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=200), unique=True, nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_sessions',
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('info', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_session_id', sa.String(255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('bot_response', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_sessions')
    op.drop_table('user_messages')
    # ### end Alembic commands ###
